openapi: 3.0.1
info:
  title: IstanzeBuoniLibroApi
  description: API Definition of IstanzeBuoniLibro
  version: 1.0.0
servers:
- url: http://localhost:8290/api/msistruzione/esb/istanzabuonolibri
paths:
  /acquisizione:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /validazione:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
