openapi: 3.0.1
info:
  title: ResidenzaSoggettoApi
  description: API Definition of ResidenzaSoggettoApi
  version: 1.0.0
servers:
- url: http://localhost:8290/api/anagrafe/esb/
paths:
  /:
    get:
      responses:
        default:
          description: Default response
